"""Remove is_superuser and add search_terms

Revision ID: 531ada5ffca7
Revises: 384ee9c2628d
Create Date: 2025-03-23 19:59:44.348072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531ada5ffca7'
down_revision = '384ee9c2628d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_terms_id'), 'search_terms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_terms_id'), table_name='search_terms')
    op.drop_table('search_terms')
    # ### end Alembic commands ### 