// src/components/LandingPage.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './LandingPage.css';

const LandingPage = () => {
  const navigate = useNavigate();
  const [activeDemo, setActiveDemo] = useState<'search' | 'insight' | 'email'>('search');

  const handleLoginClick = () => {
    navigate('/login');
  };

  const handleRegisterClick = () => {
    navigate('/register');
  };

  return (
    <div className="landing-container">
      {/* Hero Section */}
      <header className="hero-section">
        <nav className="landing-nav">
          <div className="logo">NewsAI</div>
          <div className="nav-buttons">
            <button className="login-nav-button" onClick={handleLoginClick}>Log In</button>
            <button className="register-nav-button" onClick={handleRegisterClick}>Sign Up</button>
          </div>
        </nav>

        <div className="hero-content">
          <h1>News Curated for You by AI</h1>
          <p className="hero-subtitle">
            Stay informed with personalized news insights tailored to your interests, delivered right to your inbox
          </p>
          <button className="cta-button" onClick={handleRegisterClick}>
            Get Started — It's Free
          </button>
        </div>

        <div className="hero-image">
          {/* Decorative illustration of the app interface */}
          <div className="app-preview-container">
            <div className="app-preview-mockup">
              <div className="mockup-header">
                <div className="mockup-title">Latest Insights</div>
              </div>
              <div className="mockup-content">
                <div className="mockup-insight">
                  <p>Tech giants collaborate on new AI safety standards to address concerns about rapid development.</p>
                  <div className="mockup-source">The Tech Chronicle</div>
                </div>
                <div className="mockup-insight">
                  <p>Renewable energy investments reach record high as countries accelerate climate commitments.</p>
                  <div className="mockup-source">Energy Insights</div>
                </div>
                <div className="mockup-insight">
                  <p>New research shows promising results for personalized medicine approaches in cancer treatment.</p>
                  <div className="mockup-source">Health Science Today</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Features Section */}
      <section className="features-section">
        <h2>How NewsAI Works</h2>
        <div className="features-container">
          <div className="feature-card">
            <div className="feature-icon">🔍</div>
            <h3>Personalized Search</h3>
            <p>Follow any topic you're interested in. Our AI scans thousands of sources to find relevant news.</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">💡</div>
            <h3>Smart Insights</h3>
            <p>Get concise, meaningful insights generated by AI that summarize complex topics clearly.</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">📮</div>
            <h3>Email Delivery</h3>
            <p>Receive tailored news updates straight to your inbox on a schedule that works for you.</p>
          </div>
        </div>
      </section>

      {/* Demo Section */}
      <section className="demo-section">
        <h2>See NewsAI in Action</h2>
        <div className="demo-tabs">
          <button 
            className={`demo-tab ${activeDemo === 'search' ? 'active' : ''}`}
            onClick={() => setActiveDemo('search')}
          >
            Search
          </button>
          <button 
            className={`demo-tab ${activeDemo === 'insight' ? 'active' : ''}`}
            onClick={() => setActiveDemo('insight')}
          >
            Insights
          </button>
          <button 
            className={`demo-tab ${activeDemo === 'email' ? 'active' : ''}`}
            onClick={() => setActiveDemo('email')}
          >
            Email Updates
          </button>
        </div>

        <div className="demo-content">
          {activeDemo === 'search' && (
            <div className="demo-item">
              <div className="demo-screenshot search-demo">
                <div className="demo-sidebar">
                  <div className="demo-sidebar-header">Your Topics</div>
                  <div className="demo-search-items">
                    <div className="demo-search-item">Climate Change</div>
                    <div className="demo-search-item">AI Ethics</div>
                    <div className="demo-search-item">Space Exploration</div>
                    <div className="demo-search-item active">Renewable Energy</div>
                  </div>
                  <div className="demo-search-input">
                    <input type="text" placeholder="Add new topic..." />
                  </div>
                </div>
              </div>
              <div className="demo-description">
                <h3>Follow Any Topic</h3>
                <p>Create a personalized feed by saving search terms on topics that matter to you. Add as many as you want and easily manage them.</p>
              </div>
            </div>
          )}

          {activeDemo === 'insight' && (
            <div className="demo-item">
              <div className="demo-screenshot insight-demo">
                <div className="demo-insight-card">
                  <p className="demo-insight-text">New battery technology breakthrough could double electric vehicle range while cutting charging time by 70%, according to researchers at Stanford.</p>
                  <div className="demo-source-info">Source: Tech Innovations Journal</div>
                </div>
                <div className="demo-insight-card">
                  <p className="demo-insight-text">Global solar capacity increased by 36% in 2024, with developing nations leading growth as installation costs continue to decline.</p>
                  <div className="demo-source-info">Source: Energy Reporter</div>
                </div>
              </div>
              <div className="demo-description">
                <h3>AI-Generated Insights</h3>
                <p>Our AI reads articles and extracts the most important information, giving you clear, concise summaries from trusted sources.</p>
              </div>
            </div>
          )}

          {activeDemo === 'email' && (
            <div className="demo-item">
              <div className="demo-screenshot email-demo">
                <div className="demo-email">
                  <div className="demo-email-header">
                    <div className="demo-email-subject">Your NewsAI Digest: March 28, 2025</div>
                    <div className="demo-email-from">From: updates@newsai.com</div>
                  </div>
                  <div className="demo-email-content">
                    <h3>Top Stories for Your Topics</h3>
                    <div className="demo-email-topic">
                      <h4>Renewable Energy</h4>
                      <ul>
                        <li>Offshore wind capacity tripled in Asian markets, setting new records</li>
                        <li>Green hydrogen production costs projected to decrease by 40% by 2030</li>
                      </ul>
                    </div>
                    <div className="demo-email-topic">
                      <h4>AI Ethics</h4>
                      <ul>
                        <li>New international AI governance framework adopted by 27 countries</li>
                        <li>Tech companies establish independent AI ethics review boards</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div className="demo-description">
                <h3>Stay Updated Effortlessly</h3>
                <p>Get curated news delivered straight to your inbox. Choose your frequency—daily, weekly, or real-time alerts for breaking news.</p>
              </div>
            </div>
          )}
        </div>
      </section>

      {/* Testimonials */}
      <section className="testimonials-section">
        <h2>What Our Users Say</h2>
        <div className="testimonials-container">
          <div className="testimonial-card">
            <div className="testimonial-text">
              "NewsAI has completely changed how I stay informed. The insights are relevant and save me hours of reading time each week."
            </div>
            <div className="testimonial-author">
              <div className="testimonial-name">Sarah J.</div>
              <div className="testimonial-role">Marketing Director</div>
            </div>
          </div>
          <div className="testimonial-card">
            <div className="testimonial-text">
              "I love how I can follow niche topics that mainstream news doesn't cover. The AI summaries are surprisingly insightful."
            </div>
            <div className="testimonial-author">
              <div className="testimonial-name">Michael T.</div>
              <div className="testimonial-role">Research Scientist</div>
            </div>
          </div>
          <div className="testimonial-card">
            <div className="testimonial-text">
              "The email digests are perfect for my busy schedule. I get exactly what I need to know without the noise."
            </div>
            <div className="testimonial-author">
              <div className="testimonial-name">Elena K.</div>
              <div className="testimonial-role">Startup Founder</div>
            </div>
          </div>
        </div>
      </section>

      {/* Call to Action */}
      <section className="cta-section">
        <h2>Ready to Transform How You Consume News?</h2>
        <p>Join thousands of users who are staying informed the smart way.</p>
        <div className="cta-buttons">
          <button className="cta-button large" onClick={handleRegisterClick}>
            Sign Up Now
          </button>
          <button className="secondary-button" onClick={handleLoginClick}>
            Log In
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <div className="footer-content">
          <div className="footer-logo">NewsAI</div>
          <div className="footer-links">
            <div className="footer-column">
              <h4>Product</h4>
              <ul>
                <li>Features</li>
                <li>Pricing</li>
                <li>FAQ</li>
              </ul>
            </div>
            <div className="footer-column">
              <h4>Company</h4>
              <ul>
                <li>About Us</li>
                <li>Careers</li>
                <li>Contact</li>
              </ul>
            </div>
            <div className="footer-column">
              <h4>Legal</h4>
              <ul>
                <li>Privacy Policy</li>
                <li>Terms of Service</li>
                <li>Cookie Policy</li>
              </ul>
            </div>
          </div>
        </div>
        <div className="footer-bottom">
          <p>&copy; 2025 NewsAI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;